load("@rules_cc//cc:defs.bzl", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "hello",
    srcs = ["hello.cpp"],
    deps = [
        "@urma//:urma_headers",
    ],
)

cc_binary(
    name = "device_info",
    srcs = ["device_info.cpp"],
    deps = [
        "//kbsocket/transport/raw:device_catalog",
        "//kbsocket/transport/raw:urma_api",
        "@urma//:urma_headers",
    ],
)
