# SPDX-License-Identifier: MulanPSL-2.0
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_library(
    name = "import_test_support",
    srcs = ["import_test.cpp"],
    hdrs = ["import_test.hpp"],
    deps = [
        "//kbsocket/base:scope_exit",
        "//kbsocket/transport/raw:urma_api",
        "//tools/common:control_channel",
    ],
)

cc_binary(
    name = "import_jetty_test",
    srcs = ["main.cpp"],
    deps = [":import_test_support", "@gflags"],
)

cc_test(
    name = "import_test_test",
    srcs = ["import_test_test.cpp"],
    deps = [
        ":import_test_support",
        "//kbsocket/transport/raw:urma_test_support",
        "@googletest//:gtest_main",
    ],
)
