# SPDX-License-Identifier: MulanPSL-2.0

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "no_destructor",
    hdrs = ["no_destructor.hpp"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "no_destructor_test",
    srcs = ["no_destructor_test.cpp"],
    deps = [
        ":no_destructor",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "log",
    srcs = ["log.cpp"],
    hdrs = ["log.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        ":no_destructor",
        "@gflags",
        "@spdlog",
    ],
)

cc_test(
    name = "log_test",
    srcs = ["log_test.cpp"],
    deps = [
        ":log",
        "@gflags",
        "@googletest//:gtest_main",
        "@spdlog",
    ],
)

cc_library(
    name = "scope_exit",
    hdrs = ["scope_exit.hpp"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "scope_exit_test",
    srcs = ["scope_exit_test.cpp"],
    deps = [
        ":scope_exit",
        "@googletest//:gtest_main",
    ],
)
